### ISSUE TITLE
RSS feed for `myrrlyn.net/blog`

### ISSUE THREAD

**Issue by koutheir** [myrrlyn/home#2]
I like reading your articles, thank you for your efforts!

I would like to find out about your future blog articles via RSS. Could you please provide an RSS feed for [`myrrlyn.net/blog`](https://myrrlyn.net/blog)?

**Comment by ghost** [comment]
There *is* a feed advertised at https://myrrlyn.net/blog/atom.xml that I used for some time, but recently (at some point after https://myrrlyn.net/blog/ferrilab/introducing-ferrilab, that's the last post my reader has) it seems to have started returning a 500.

**Comment by hdhoang** [comment]
for now, I subscribe to the content repo's commit log https://github.com/myrrlyn/website-content/commits.atom

**Comment by koutheir** [comment]
Nobody seems to care about this issue. Closing.
